services:
  - type: web
    name: whatsapp-web-bot
    env: node
    plan: free
    buildCommand: |
      rm -rf node_modules
      npm install
      apt-get update && apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      apt-get update && apt-get install -y google-chrome-stable
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUPPETEER_CACHE_DIR
        value: /tmp/.puppeteer_cache
