services:
  - type: web
    name: whatsapp-web-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'
      - key: PUPPETEER_CACHE_DIR
        value: /tmp/.puppeteer_cache
