services:
  - type: web
    name: whatsapp-web-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUPPETEER_CACHE_DIR
        value: /var/data/.puppeteer_cache
    disks:
      - name: puppeteer_cache
        mountPath: /var/data/.puppeteer_cache
        sizeGB: 512MB
